trigger:
     - master

pool:
  vmImage: 'vs2017-win2016'

steps:
- task: PowerShell@2
  displayName: 'PowerShell Script'
  inputs:
    targetType: filePath
    filePath: '$(System.DefaultWorkingDirectory)/database/get-latest-submodules.ps1'

- task: MSBuild@1
  inputs:
    solution: '**\*.sln' 
    msbuildVersion: 'latest'
    configuration: 'Release'
    msbuildArchitecture: 'x64'

