trigger:
  branches:
   include:
     - refs/tags/release

pool:
  vmImage: 'vs2017-win2016'

steps:
- task: PowerShell@2
  displayName: 'PowerShell Script'
  inputs:
    targetType: filePath
    filePath: '$(System.DefaultWorkingDirectory)/database/get-latest-submodules.ps1'

- task: VSBuild@1
  inputs:
    solution: '**\*.sln' 
    vsVersion: 'latest'
    configuration: 'Release'
    msbuildArchitecture: 'x64'