trigger:
     - master

pool:
  vmImage: 'vs2017-win2016'

steps:
- task: PowerShell@2
  displayName: 'PowerShell Script'
  inputs:
    targetType: filePath
    filePath: '$(System.DefaultWorkingDirectory)/database/get-latest-submodules.ps1'

- task: MSBuild@1
  inputs:
    solution: '**\*.sln' 
    msbuildVersion: 'latest'
    configuration: 'Release'
    msbuildArchitecture: 'x64'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    Contents: |
      $(Build.SourcesDirectory)\checkmk\bin\**\*
      $(Build.SourcesDirectory)\database\bin\**\*.dacpac
      $(Build.SourcesDirectory)\collector\*
      $(Build.SourcesDirectory)\configg\*
      $(Build.SourcesDirectory)\cis-benchmark\*
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'