/*



*/

CREATE FUNCTION [system].[get_datetimeoffset]  
(
	@datetime DATETIME2 = NULL
)
RETURNS TABLE
WITH ENCRYPTION
RETURN(
	SELECT TODATETIMEOFFSET(@datetime, DATEPART(TZOFFSET, SYSDATETIMEOFFSET())) AS [datetimeoffset]
)
